version: '3.8'

services:
  emulator:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    networks:
      - default

networks:
  default:
    driver: bridge
