on:
  push:
    branches: [ main ]
name: Verifying code
jobs:
  web-deploy:
    name: Compiling
    runs-on: ubuntu-latest
    steps:
    - name: Fetching latest code
      uses: actions/checkout@v3
      
    - name: Compiling
      run: ./compile.sh

    - name: Testing operations
      run: ./testing_operations.sh
      
