on:
  push:
    branches: [ main ]
name: Compile and Test
jobs:
  web-deploy:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
    - name: Fetching latest code
      uses: actions/checkout@v3

    - name: Compile & Testing
      run: ./test_cpu.sh
      
